export const ARTIST_TYPE = "ARTIST_TYPE";
export const ARTISTS_INFO = "ARTISTS_INFO";
export const LOAD_USER = "LOAD_USER";
export const CURRENT_ARTIST = "CURRENT_ARTIST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const LOGOUT_USER = "LOGOUT_USER";
